import PptxGenJS from 'pptxgenjs';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Header, ImageRun, Table, TableRow, TableCell, WidthType, BorderStyle } from 'docx';
import JSZip from 'jszip';

import { Course, CourseStep, SlideModel, SlideArchetype, SlideRules } from '../types';
import { SlideState } from '../types/slideState';
import { replaceBlobUrlsWithPublic, ensurePublicExternalImages } from './imageService';
import { isEnabled } from '../config/featureFlags';
import { exportCourseAsPdf } from './pdfExporter';
import { SlideDesignJSON, getSmartFallbackDesign } from './presentationAiService';
import { searchImages } from './imageSearchService';
import { 
    renderHeroSlide, 
    renderSplitLeft, 
    renderSplitRight, 
    renderBigStat, 
    renderComparison, 
    renderQuotation, 
    renderTimeline, 
    renderDefault,
    renderFullImage,
    renderGridCards,
    renderImageCenter,
    renderThreeColumns,
    renderSectionHeader,
    renderChecklist,
    renderDoDont,
    renderProcessSteps,
    renderTableSimple,
    renderAgendaCompact
} from '../lib/pptx/templates';
import { validateSemantic, pickCompatibleLayout } from '../lib/pptx/contracts';
import TurndownService from 'turndown';
import { LAYOUT_TOKEN_MAPPING } from '../constants/slideLayouts';
import { getParsingKeywords } from '../lib/slideParsingLocales';

// ============================================================================
// TYPES & INTERFACES
// ============================================================================

export interface ContentSection {
    title: string;
    bulletPoints: string[];
    images: { url: string; alt: string }[];
    rawContent: string;
    bodyText?: string;
    speakerNotes?: string;
    visualSearchTerm?: string;
    slideLayout?: SlideArchetype;
    adaptedContent?: Record<string, string>;
}

const normalizeExternalImageLinks = (md: string): string => {
    try {
        let out = md;
        out = out.replace(/https?:\/\/unsplash\.com\/photos\/[\S)]+/gi, (m) => {
            const last = (m.split('/').pop() || '').split('?')[0];
            const id = last.includes('-') ? (last.split('-').pop() || last) : last;
            return `https://source.unsplash.com/${id}/1600x900`;
        });
        out = out.replace(/https?:\/\/(?:www\.)?pexels\.com\/photo\/[\w-]*?(\d+)\/?/gi, (_m: string, id: string) => {
            const safeId = String(id);
            return `https://images.pexels.com/photos/${safeId}/pexels-photo-${safeId}.jpeg?auto=compress&cs=tinysrgb&w=1600&h=900`;
        });
        out = out.replace(/https?:\/\/(?:www\.)?pixabay\.com\/photos\/[\w-]*?(\d+)\/?/gi, (_m: string, id: string) => {
            const safeId = String(id);
            return `https://cdn.pixabay.com/photo/${safeId}_1280.jpg`;
        });
        return out;
    } catch {
        return md;
    }
};

const looksLikeHtml = (s: string): boolean => /<[a-z][\s\S]*>/i.test(s || '');

// ============================================================================
// HELPER FUNCTIONS - SLIDE GENERATORS
// ============================================================================

const addTitleSlide = (pptx: PptxGenJS, course: Course): void => {
    const slide = pptx.addSlide();
    slide.background = { color: '1E3A8A' };

    slide.addText(course.title, {
        x: 0.5, y: 2, w: '90%', h: 1.5,
        fontSize: 44, bold: true, color: 'FFFFFF',
        align: 'center'
    });

    slide.addText(course.subject, {
        x: 0.5, y: 3.5, w: '90%', h: 0.8,
        fontSize: 24, color: 'E5E7EB',
        align: 'center'
    });

    slide.addText('Generated by CourseCopilot', {
        x: 0.5, y: 6.5, w: '90%', h: 0.3,
        fontSize: 12, color: '9CA3AF',
        align: 'center', italic: true
    });
};

/*
const addAgendaSlide = (
    pptx: PptxGenJS,
    course: Course,
    structureStep: CourseStep | null,
    videoScriptStep: CourseStep | null
): void => {
    const slide = pptx.addSlide();

    slide.addText('Structura Cursului', {
        x: 0.5, y: 0.5, w: '90%', h: 0.8,
        fontSize: 32, bold: true, color: '1F2937'
    });

    const modules = structureStep
        ? parseModulesFromStructure(structureStep.content)
        : generateModulesFromSteps(course.steps || []);

    slide.addText(modules, {
        x: 0.5, y: 1.5, w: '90%', h: 5,
        fontSize: 18, bullet: true, color: '374151',
        lineSpacing: 28
    });

    if (videoScriptStep) {
        const introScript = extractIntroScript(videoScriptStep.content);
        if (introScript) {
            slide.addNotes(introScript);
        }
    }
};
*/

/*
const _addContentSlides = async (
    pptx: PptxGenJS,
    step: CourseStep,
    course: Course
): Promise<void> => {
    const pre = normalizeExternalImageLinks(step.content);
    const withPublic = await replaceBlobUrlsWithPublic(pre, course.user_id, course.id);
    const sections = parseContentSections(withPublic, course.language);

    for (const section of sections) {
        const slide = pptx.addSlide();

        // Slide Title
        slide.addText(section.title, {
            x: 0.5, y: 0.5, w: '90%', h: 0.8,
            fontSize: 28, bold: true, color: '1F2937'
        });

        // Content Bullets
        if (section.bulletPoints.length > 0) {
            const bulletText = section.bulletPoints.join('\n');
            slide.addText(bulletText, {
                x: 0.5, y: 1.5, w: '50%', h: 4, // Reduced width to make room for image
                fontSize: 18, bullet: true, color: '374151',
                lineSpacing: 28
            });
        } else if (section.bodyText) {
            slide.addText(section.bodyText, {
                x: 0.5, y: 1.5, w: '50%', h: 4.8,
                fontSize: 20, color: '374151',
                lineSpacing: 28
            });
        }

        // Handle Visuals (Placeholder or Real Image)
        const yPos = 1.5;
        // Check for Visual Search Term first (New Flow)
        if (section.visualSearchTerm) {
             // For now, use a safer placeholder logic
             // Extract just the first few meaningful words to avoid 503 errors from long queries
             const STOP = ['si','și','the','and','of','for','în','cu','la','din','pe','un','o','este','sunt','de','că','ca','的','和','是','在','de','e','para','em','uma','um','dos','das','ao','à'];
             const keywords = section.visualSearchTerm
                .toLowerCase()
                .split(/[\s,]+/)
                .filter(w => w.length > 3 && !STOP.includes(w))
                .slice(0, 4)
                .join(' ');
             
             let imageUrl: string | undefined;
             try {
                 const results = await searchImages(keywords || 'business');
                 if (results && results.length > 0) {
                     imageUrl = await fetchToDataUrl(results[0].url) || undefined;
                 }
             } catch (e) {
                 console.warn('Visual search failed:', e);
             }

             if (imageUrl) {
                 slide.addImage({ 
                     data: imageUrl, 
                     x: 5.8, y: yPos, w: 4, h: 3 
                 });
             } else {
                 // Fallback: Gray placeholder box if image fetch fails
                 slide.addText('Image Placeholder', { 
                     x: 5.8, y: yPos, w: 4, h: 3, 
                     fill: { color: 'F3F4F6' }, align: 'center', color: '9CA3AF' 
                 });
             }
        } 
        // Fallback to legacy embedded images or Smart Title Search
        else if (section.images.length > 0) {
            for (const img of section.images.slice(0, 1)) {
                try {
                    let dataUrl: string | null = null;
                    if (img.url.startsWith('http')) {
                        dataUrl = await fetchToDataUrl(img.url);
                    }
                    const isData = img.url.startsWith('data:') || !!dataUrl;
                    const opts: PptxGenJS.ImageProps = isData
                        ? { data: dataUrl || img.url, x: 5.8, y: yPos, w: 4, h: 3 }
                        : img.url.startsWith('http')
                            ? { path: img.url, x: 5.8, y: yPos, w: 4, h: 3 }
                            : null as unknown as PptxGenJS.ImageProps;
                    if (!opts) continue;
                    slide.addImage(opts);
                } catch (e) {
                    console.warn('Failed to add image:', e);
                }
            }
        } else {
             // NEW: Smart Title Search Fallback
             // If no visual tag AND no existing image, try searching Unsplash using the slide title
             // This ensures we don't have empty slides
             const keywords = section.title
                .split(/[\s,]+/)
                .filter(w => w.length > 3)
                .slice(0, 3)
                .join(' ');
                
             if (keywords) {
                    try {
                        const results = await searchImages(keywords);
                        if (results && results.length > 0) {
                            const dataUrl = await fetchToDataUrl(results[0].url);
                            if (dataUrl) {
                                slide.addImage({ 
                                    data: dataUrl, 
                                    x: 5.8, y: yPos, w: 4, h: 3 
                                });
                            }
                        }
                    } catch (e) {
                        console.warn('Title search failed:', e);
                    }
             }
        }

        // Speaker Notes
        // REMOVED as per user request to prevent corruption/issues
        // const notes = section.speakerNotes || findMatchingScript(videoScripts, section.title);
        // if (notes) {
        //    slide.addNotes(notes);
        // }

        // Footer
        slide.addText(`${course.title} | ${new Date().toLocaleDateString()}`, {
            x: 0.5, y: 6.8, w: '90%', h: 0.3,
            fontSize: 10, color: '9CA3AF', align: 'right'
        });
    }
};
*/

/*
const addSummarySlide = (pptx: PptxGenJS): void => {
    const slide = pptx.addSlide();
    slide.background = { color: 'F3F4F6' };

    slide.addText('Recapitulare', {
        x: 0.5, y: 1.5, w: '90%', h: 1,
        fontSize: 36, bold: true, color: '1F2937',
        align: 'center'
    });

    const summaryText = [
        'Mulțumim pentru participare!',
        'Continuați cu proiectele practice',
        'Descărcați cheat sheet-ul pentru referință rapidă',
        'Aplicați tehnicile învățate în următoarele 48h'
    ].join('\n');

    slide.addText(summaryText, {
        x: 0.5, y: 3, w: '90%', h: 3,
        fontSize: 20, bullet: true, color: '374151',
        align: 'center', lineSpacing: 32
    });
};
*/

const fetchToDataUrl = async (url: string): Promise<string | null> => {
    const toDataUrl = async (blob: Blob) => new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(reader.result as string);
        reader.onerror = reject;
        reader.readAsDataURL(blob);
    });
    const tryFetch = async (u: string): Promise<string | null> => {
        try {
            const res = await fetch(u, { cache: 'no-store' });
            if (!res.ok) return null;
            const blob = await res.blob();
            const looksImage = blob.type.startsWith('image/') || /\.(png|jpg|jpeg|gif|webp)$/i.test(u);
            if (!looksImage) {
                console.warn(`[Export] Non-image content-type for ${u}: ${blob.type}`);
                // Still attempt conversion
            }
            return await toDataUrl(blob);
        } catch {
            return null;
        }
    };
    return (await tryFetch(url)) || (await tryFetch(`https://cors.isomorphic-git.org/${url}`));
};

const normalizeNotesText = (text: string): string => {
    const plain = text
        .replace(/[*_~`>#-]/g, '')
        .replace(/\[(.*?)\]\((.*?)\)/g, '$1')
        .replace(/\s+/g, ' ')
        .trim();
    const noEmoji = plain.replace(/\p{Extended_Pictographic}/gu, '');
    const nfc = noEmoji.normalize('NFC');
    const limited = nfc.length > 1500 ? nfc.slice(0, 1497) + '…' : nfc;
    return limited;
};

// ============================================================================
// PARSER FUNCTIONS
// ============================================================================

export const normalizeLayoutToken = (token: string): string => {
    return (token || '').trim().toUpperCase().replace(/[\s\-]+/g, '_');
};

export const mapTokenToArchetype = (token: string): SlideArchetype => {
    const t = normalizeLayoutToken(token);

    if (t in LAYOUT_TOKEN_MAPPING) {
        return LAYOUT_TOKEN_MAPPING[t];
    }

    // Default fallback is handled by caller or defaults to Default/Explainer
    return SlideArchetype.Explainer;
};

export const sanitizeText = (text: string): string => {
    // Remove control characters that are not allowed in XML (0x00-0x08, 0x0B-0x0C, 0x0E-0x1F)
    // Keep tabs (0x09), newlines (0x0A), carriage returns (0x0D)
    return text.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\uFFFE\uFFFF]/g, '');
};

export const parseContentSections = (markdown: string, language: string = 'en'): ContentSection[] => {
    const sections: ContentSection[] = [];
    const keywords = getParsingKeywords(language);
    const slideIdentifierPattern = keywords.slideIdentifier.join('|');
    
    // --- 0. PRE-CLEANING (Fix for Markdown Code Blocks) ---
    // Remove ```xml, ```markdown, or ``` wrappers if present
    // Enhanced regex to handle optional whitespace before/after and various language tags
    markdown = markdown
        .replace(/^\s*```(?:xml|html|markdown|text)?\s*[\r\n]+/, '')
        .replace(/[\r\n]+\s*```\s*$/, '');

    // --- 1. XML-BASED PARSING (STRICT MODE) ---
    // Căutăm blocuri <SLIDE_BEGIN ...> ... <SLIDE_END ...> SAU <SLIDE_START ...>
    // Suportă id="1", id='1', spații flexibile, și START/BEGIN
    const slideBlockRegex = /<SLIDE_(?:BEGIN|START)\s+id=["']?([^"' >]+)["']?>([\s\S]*?)<SLIDE_(?:END|STOP)\s+id=["']?\1["']?>/gi;
    let match;
    let hasXmlSlides = false;

    while ((match = slideBlockRegex.exec(markdown)) !== null) {
        hasXmlSlides = true;
        const slideId = match[1];
        const blockContent = match[2];

        // Extragem componentele interne
        const extractTag = (tag: string, content: string) => {
            const regex = new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`, 'i');
            const m = content.match(regex);
            return m ? m[1].trim() : '';
        };

        const title = extractTag('TITLE', blockContent);
        const visual = extractTag('VISUAL', blockContent);
        const contentBody = extractTag('CONTENT', blockContent);
        const notes = extractTag('NOTES', blockContent);

        // Detectare layout metadata din comentarii HTML
        let slideLayout: SlideArchetype | undefined;
        const layoutMatch = blockContent.match(/<!--\s*slide-layout:\s*([A-Za-z0-9_\-\s]+)\s*-->/i);
        if (layoutMatch) {
            slideLayout = mapTokenToArchetype(layoutMatch[1]);
        }

        // Detectare adapted content metadata din comentarii HTML
        let adaptedContent: Record<string, string> = {};
        const adaptedMatch = blockContent.match(/<!--\s*slide-adapted:\s*([A-Za-z0-9_\-\s]+)\s*\|\s*(.+?)\s*-->/i);
        if (adaptedMatch) {
            const rawKey = adaptedMatch[1].trim();
            const canonicalKey = normalizeLayoutToken(rawKey);
            adaptedContent[canonicalKey] = adaptedMatch[2].trim();
            const arche = mapTokenToArchetype(rawKey);
            adaptedContent[String(arche)] = adaptedMatch[2].trim();
        }

        // Procesare bullets din CONTENT
        let bulletPoints: string[] = [];
        let bodyText = '';
        if (contentBody) {
             const lines = contentBody.split('\n');
             lines.forEach(line => {
                 const trimmed = line.trim();
                 if (/^[-*•]\s+/.test(trimmed)) {
                     bulletPoints.push(trimmed.replace(/^[-*•]\s+/, ''));
                 } else if (/^\d+\.\s+/.test(trimmed)) {
                     bulletPoints.push(trimmed.replace(/^\d+\.\s+/, ''));
                 } else if (trimmed.length > 0) {
                     bodyText += (bodyText ? '\n' : '') + trimmed;
                 }
             });
        }
        
        // Dacă nu avem bullets dar avem bodyText, încercăm să-l folosim ca bullets
        if (bulletPoints.length === 0 && bodyText.length > 0) {
             bulletPoints = bodyText.split('\n');
             bodyText = '';
        }

        // Adăugăm secțiunea
        sections.push({
            title: title || `Slide ${slideId}`,
            bulletPoints: bulletPoints.map(sanitizeText),
            images: [], // Imaginile inline nu sunt suportate momentan în XML strict, se bazează pe Visual Search
            rawContent: blockContent,
            bodyText: sanitizeText(bodyText),
            visualSearchTerm: visual,
            speakerNotes: sanitizeText(notes),
            slideLayout,
            adaptedContent // Adaptarea este acum mapată din XML
        });
    }

    if (hasXmlSlides) {
        return sections;
    }

    // --- 2. LEGACY PARSING (FALLBACK) ---
    const lines = markdown.split('\n');
    let currentTitle: string | null = null;
    let currentBuffer: string[] = [];

    const flush = () => {
        if (currentTitle && currentBuffer.length > 0) {
            processSlideBlock(currentTitle, currentBuffer.join('\n'), sections, language);
        }
        currentTitle = null;
        currentBuffer = [];
    };

    for (let i = 0; i < lines.length; i++) {
        const raw = lines[i];
        const line = raw.trim();

        // --- DETECT NEW SLIDE START (PRIORITIZE "Slide nr:") ---
        // Accept "Slide 1", "Slide [1]", "Slide (1)" with or without a title part, optional colon
        const slideMatchRegex = new RegExp(`^(\\*\\*|#+)?\\s*(${slideIdentifierPattern})\\s*(nr\\.|#)?\\s*[\\[\\(]?\\d+[\\]\\)]?(?:\\s*[:：]\\s*(.+?))?(\\*\\*|#+)?$`, 'i');
        const slideMatch = line.match(slideMatchRegex);
        let headerMatch = line.match(/^(#{1,6})\s+(.+)$/);
        
        // Prevent H3-H6 from breaking slides unless they are explicitly named "Slide ..."
        // This fixes issues with "Trainer Flow" where H3 is used for internal sections (Visual/Text/Notes)
        if (headerMatch && headerMatch[1].length > 2 && !slideMatch) {
            headerMatch = null;
        }

        // module headers intentionally ignored to avoid over-segmentation
        const hrMatch = line.match(/^(\-{3,}|\*{3,})$/);

        if (slideMatch || headerMatch || hrMatch) {
            flush();
            let rawTitle = '';
            if (slideMatch) rawTitle = (slideMatch[4] || 'Slide').toString();
            else if (headerMatch) rawTitle = headerMatch[2];
            else if (hrMatch) rawTitle = 'Slide';
            currentTitle = rawTitle.replace(/(\*\*|#+)$/, '').trim();
            continue;
        }

        if (currentTitle) {
            currentBuffer.push(raw);
        } else if (line.length > 0) {
            // IMPLICIT START: Found content before any explicit slide header
            // Treat this as the start of the first slide
            currentTitle = 'Slide 1';
            currentBuffer.push(raw);
        }
    }

    flush();

    // --- 3. IMPLICIT SLIDE DETECTION (RECOVERY MODE) ---
    // If we only found 1 slide (or 0) and the content is long, it might be a malformed generation
    // where "Slide X" headers are missing. We try to split by visual description paragraphs.
    if (sections.length <= 1 && markdown.length > 200) {
        const potentialImplicitSlides = detectImplicitSlides(markdown);
        if (potentialImplicitSlides.length > 1) {
             console.log('[SlideParser] Recovery: Detected implicit slides:', potentialImplicitSlides.length);
             return potentialImplicitSlides;
        }
    }

    return sections;
};

const detectImplicitSlides = (markdown: string): ContentSection[] => {
    // Heuristic: Look for paragraphs that start with specific visual cues (especially for Romanian 'Un', 'O', 'Două', etc.)
    // followed by content.
    const chunks = markdown.split(/\n\n+/);
    const newSections: ContentSection[] = [];
    let currentSection: ContentSection | null = null;
    
    // Keywords that likely start a visual description in this specific failure mode
    const visualStarts = ['Un ', 'O ', 'Două ', 'Trei ', 'Patru ', 'Cinci ', 'Imagine ', 'Vizual ', 'Grafic ', 'A ', 'An ', 'The ', 'Two ', 'Three '];
    
    chunks.forEach((chunk) => {
        const trimmed = chunk.trim();
        if (!trimmed) return;
        
        // Check if this chunk looks like a new Visual Description (Start of Slide)
        // It must start with one of the keywords AND not be a bullet/list
        const isVisualStart = visualStarts.some(v => trimmed.startsWith(v)) && 
                              !trimmed.startsWith('-') && 
                              !trimmed.startsWith('*') && 
                              !trimmed.startsWith('#') &&
                              !trimmed.match(/^\d+\./);

        // Always treat the first chunk as a start if we don't have one
        if (isVisualStart || newSections.length === 0) {
             currentSection = {
                title: `Slide ${newSections.length + 1}`,
                bulletPoints: [],
                images: [],
                rawContent: trimmed,
                bodyText: '',
                visualSearchTerm: trimmed, // Assume the paragraph IS the visual description
                speakerNotes: '',
                slideLayout: undefined
             };
             newSections.push(currentSection);
        } else if (currentSection) {
             // Append to current section
             // If it looks like a script (starts with "Salutare", "Hello", etc) or list
             if (trimmed.startsWith('-') || trimmed.startsWith('*')) {
                 // It's bullets
                 const bullets = trimmed.split('\n').map(l => l.replace(/^[-*•]\s+/, '').trim());
                 currentSection.bulletPoints.push(...bullets);
             } else {
                 // It's body text / script
                 currentSection.bodyText += (currentSection.bodyText ? '\n\n' : '') + trimmed;
                 // Also populate speaker notes as fallback
                 currentSection.speakerNotes += (currentSection.speakerNotes ? '\n\n' : '') + trimmed;
             }
             currentSection.rawContent += '\n\n' + trimmed;
        }
    });

    return newSections.length > 1 ? newSections : [];
};

const processSlideBlock = (title: string, contentBlock: string, sections: ContentSection[], language: string = 'en') => {
    const lines = contentBlock.trim().split('\n');
    
    let currentMode: 'content' | 'notes' | 'visual' | null = null;
    let visualSearchTerm = '';
    let speakerNotes = '';
    let slideLayout: SlideArchetype | undefined;
    let adaptedContent: Record<string, string> = {};
    let bulletPoints: string[] = [];
    let images: { url: string; alt: string }[] = [];
    let bodyTextParts: string[] = [];

    const keywords = getParsingKeywords(language);
    const slideIdentifierPattern = keywords.slideIdentifier.join('|');
    
    // Helper regex construction
    const buildRegex = (words: string[]) => {
        const pattern = words.join('|'); // Assume words don't have regex special chars for now
        return new RegExp(`^\\s*[-*•_#]*\\s*(\\*\\*|__)?\\s*(${pattern})\\s*(\\*\\*|__)?\\s*[:：\\-]?\\s*`, 'i');
    };

    const visualRegex = buildRegex(keywords.visual);
    const textRegex = buildRegex(keywords.text);
    const notesRegex = buildRegex(keywords.notes);
    const titleLabelRegex = buildRegex(keywords.title);
    const imageLabelRegex = buildRegex(keywords.visual); // Often overlaps with visual

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line) continue;

        // --- FILTER OUT NOISE ---
        // If the line looks like a Slide title or Module header that slipped in (handling bold/headers)
        const noiseRegex = new RegExp(`^(\\*\\*|#+)?\\s*(${slideIdentifierPattern}|Modul[e]?)\\s*#?\\s*[\\[\\(]?\\d+[\\]\\)]?:`, 'i');
        if (noiseRegex.test(line)) continue;
        if (line.startsWith('---')) continue;

        // --- DETECT LAYOUT METADATA ---
        const layoutMatch = line.match(/^<!--\s*slide-layout:\s*([A-Za-z0-9_\-\s]+)\s*-->/i);
        const layoutDivMatch = line.match(/<div\s+data-slide-layout="([^"]+)"/i);
        
        if (layoutMatch) {
            const rawToken = layoutMatch[1];
            slideLayout = mapTokenToArchetype(rawToken);
            continue;
        }
        if (layoutDivMatch) {
            const rawToken = layoutDivMatch[1];
            slideLayout = mapTokenToArchetype(rawToken);
            continue;
        }

        // --- DETECT HIDDEN IMAGE ---
        const imageDivMatch = line.match(/<div\s+data-slide-image="([^"]+)"(?:\s+data-slide-image-alt="([^"]*)")?/i);
        if (imageDivMatch) {
            images.push({
                url: imageDivMatch[1],
                alt: imageDivMatch[2] || ''
            });
            continue;
        }

        // --- DETECT ADAPTED CONTENT METADATA ---
        const adaptedMatch = line.match(/^<!--\s*slide-adapted:\s*([A-Za-z0-9_\-\s]+)\s*\|\s*(.+?)\s*-->/i);
        if (adaptedMatch) {
            const rawKey = adaptedMatch[1].trim();
            const canonicalKey = normalizeLayoutToken(rawKey);
            adaptedContent[canonicalKey] = adaptedMatch[2].trim();
            const arche = mapTokenToArchetype(rawKey);
            adaptedContent[String(arche)] = adaptedMatch[2].trim();
            continue;
        }

        // --- DETECT MODE SWITCHERS ---
        // Handle "Label: Content" on the same line
        if (visualRegex.test(line)) {
            currentMode = 'visual';
            const content = line.replace(visualRegex, '').trim();
            if (content) visualSearchTerm = content;
            continue;
        }

        if (textRegex.test(line)) {
            currentMode = 'content';
            const content = line.replace(textRegex, '').trim();
            // If there is content on the same line, process it immediately
            if (content) {
                if (content.startsWith('- ') || content.startsWith('* ') || content.startsWith('• ')) {
                    bulletPoints.push(content.replace(/^[-*•]\s+/, '').trim());
                } else {
                    bodyTextParts.push(content);
                }
            }
            continue;
        }

        if (notesRegex.test(line)) {
            currentMode = 'notes';
            const content = line.replace(notesRegex, '').trim();
            if (content) speakerNotes += (speakerNotes ? '\n' : '') + content;
            continue;
        }

        // --- PROCESS LINE BASED ON MODE ---
        if (currentMode === 'visual') {
            if (!visualSearchTerm) visualSearchTerm = line;
            else visualSearchTerm += ' ' + line;
        } else if (currentMode === 'notes') {
            // Collect notes lines verbatim (plain text)
            speakerNotes += (speakerNotes ? '\n' : '') + line;
        } else if (currentMode === 'content') {
            // Content Mode
            if (line.toLowerCase().includes('layout:')) continue;
            // Ignore labels that should never become content
            if (titleLabelRegex.test(line)) continue;
            if (imageLabelRegex.test(line)) continue;
            if (visualRegex.test(line)) { currentMode = 'visual'; continue; }
            if (notesRegex.test(line)) { currentMode = 'notes'; continue; }

            // Check for bullets (tolerant to indentation)
            if (/^\s*[-*•]\s+/.test(line)) {
                bulletPoints.push(line.replace(/^\s*[-*•]\s+/, '').trim());
            } else if (/^\s*\d+\.\s+/.test(line)) {
                bulletPoints.push(line.replace(/^\s*\d+\.\s+/, '').trim());
            } else if (/^\s*!\[/.test(line)) {
                const match = line.match(/!\[([^\]]*)\]\(([^)]+)\)/);
                if (match) images.push({ alt: match[1], url: match[2] });
            } else {
                // Regular text line
                // Aggressively filter out things that look like metadata keys if they lack the colon
                if (line.length > 2) {
                    bodyTextParts.push(line);
                }
            }
        } else {
            // Fallback: if no explicit \"Text\" label was detected, treat non-label lines as content
            if (visualRegex.test(line)) { currentMode = 'visual'; continue; }
            if (notesRegex.test(line)) { currentMode = 'notes'; continue; }
            if (!titleLabelRegex.test(line) && !imageLabelRegex.test(line)) {
                if (/^\s*[-*•]\s+/.test(line)) {
                    bulletPoints.push(line.replace(/^\s*[-*•]\s+/, '').trim());
                } else if (/^\s*\d+\.\s+/.test(line)) {
                    bulletPoints.push(line.replace(/^\s*\d+\.\s+/, '').trim());
                } else if (/^\s*!\[/.test(line)) {
                    const match = line.match(/!\[([^\]]*)\]\(([^)]+)\)/);
                    if (match) images.push({ alt: match[1], url: match[2] });
                } else if (line.length > 2) {
                    bodyTextParts.push(line);
                }
            }
        }
    }

    if (bulletPoints.length === 0 && bodyTextParts.length > 0) {
         bulletPoints = bodyTextParts.map(l => l.replace(/^\s*[-*•]\s+/, '').trim());
         bodyTextParts = [];
    }

    // LIMIT CONTENT DENSITY
    // If we have too many bullets, take the first 7 to prevent overflow
    if (bulletPoints.length > 7) {
        bulletPoints = bulletPoints.slice(0, 7);
    }

    // Clean up bullets that might have captured labels/headers
    bulletPoints = bulletPoints.filter(b => 
        !/^(Slide|Modul[e]?)\s*#?\s*[\[\(]?\d+[\]\)]?:/i.test(b) &&
        !/^---$/.test(b) &&
        !/^\s*[-*•_#]*\s*(Titlu|Subtitlu|Imagine\s*Sugerată|Speaker\s*Notes|Visual|Image|Visual\s*cue|Prompt|Vizual|Imagem|Note\s*Vorbit|Note\s*Trainer|Text|Content|Conținut|Texto)\s*(\*\*|__)?\s*[:：\-]/i.test(b)
    );

    // SANITIZE TEXT to prevent XML corruption
    const cleanTitle = sanitizeText(title.replace(/^(Slide|Modul[e]?)\s*#?\s*[\[\(]?\d+[\]\)]?:\s*/i, '').trim());
    const cleanBullets = bulletPoints.map(sanitizeText);
    const cleanBody = sanitizeText(bodyTextParts.join('\n'));
    const cleanNotes = sanitizeText(speakerNotes);

    let finalTitle = cleanTitle;
    const isPlaceholderTitle = !finalTitle || /^slide(\s*\d+)?$/i.test(finalTitle);
    if (isPlaceholderTitle) {
        if (cleanBullets.length > 0) {
            finalTitle = cleanBullets[0];
            cleanBullets.shift();
        } else {
            const firstBody = (cleanBody.split('\n').filter(Boolean)[0] || '').trim();
            if (firstBody) {
                finalTitle = firstBody;
            } else {
                finalTitle = cleanTitle || 'Slide fără titlu';
            }
        }
    }

    sections.push({
        title: finalTitle,
        bulletPoints: cleanBullets,
        images,
        rawContent: contentBlock,
        bodyText: cleanBody,
        visualSearchTerm,
        speakerNotes: cleanNotes,
        slideLayout,
        adaptedContent
    });
};

const parseVideoScripts = (markdown: string): Record<string, string> => {
    const scripts: Record<string, string> = {};
    const lessons = markdown.split(/\n(?=## )/);

    for (const lesson of lessons) {
        const titleMatch = lesson.match(/^##\s*(.+)/m);
        if (!titleMatch) continue;

        const title = titleMatch[1].trim();
        const audioMatches = lesson.matchAll(/\[AUDIO\]\s*(.+?)(?=\[VISUAL\]|\n\n|$)/gs);
        const audioContent = Array.from(audioMatches)
            .map(m => m[1].trim())
            .join('\n\n');

        if (audioContent) {
            scripts[title] = audioContent;
        }
    }

    return scripts;
};

const findMatchingScript = (
    scripts: Record<string, string>,
    slideTitle: string
): string | null => {
    if (scripts[slideTitle]) {
        return scripts[slideTitle];
    }

    const keywords = slideTitle.toLowerCase().split(' ').filter(w => w.length > 3);
    for (const [scriptTitle, content] of Object.entries(scripts)) {
        const matches = keywords.filter(kw =>
            scriptTitle.toLowerCase().includes(kw)
        );
        if (matches.length >= 2) {
            return content;
        }
    }

    return null;
};

/*
const extractIntroScript = (markdown: string): string => {
    const introMatch = markdown.match(/\[AUDIO\]\s*(.+?)(?=\[VISUAL\]|\n##|$)/s);
    return introMatch ? introMatch[1].trim() : '';
};

const parseModulesFromStructure = (markdown: string): string => {
    const lines = markdown.split('\n');
    const modules: string[] = [];

    for (const line of lines) {
        if (line.match(/^(Modul|Module)\s+\d+:/i)) {
            modules.push(line.trim());
        } else if (line.match(/^\s*[*-]\s+\*\*Lecția/i)) {
            modules.push('  ' + line.trim().replace(/^\s*[*-]\s+/, ''));
        }
    }

    return modules.length > 0 ? modules.join('\n') : 'Structura cursului va fi detaliată în lecțiile următoare.';
};

const generateModulesFromSteps = (steps: CourseStep[]): string => {
    return steps
        .filter(s => !shouldExcludeFromSlides(s))
        .map((s, i) => `${i + 1}. ${s.title_key}`)
        .join('\n');
};
*/

const shouldExcludeFromSlides = (step: CourseStep): boolean => {
    const excludedKeys = ['structure', 'video_scripts', 'tests', 'cheat_sheets'];
    return excludedKeys.some(key => step.title_key.toLowerCase().includes(key));
};

const findStepByKey = (course: Course, keyPattern: string): CourseStep | null => {
    return course.steps?.find(s =>
        s.title_key.toLowerCase().includes(keyPattern.toLowerCase())
    ) || null;
};

// ============================================================================
// MAIN EXPORT FUNCTIONS
// ============================================================================

const exportCourseAsPptxV2 = async (course: Course): Promise<void> => {
    const pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_16x9';

    // 1. Title Slide
    addTitleSlide(pptx, course);

    // 2. Agenda Slide - REMOVED per user request
    // const structureStep = findStepByKey(course, 'structure');
    // const videoScriptStep = findStepByKey(course, 'video_scripts');
    // addAgendaSlide(pptx, course, structureStep, videoScriptStep);
    // const scripts = videoScriptStep ? parseVideoScripts(videoScriptStep.content) : {};
    const scripts = {}; // Initialize empty scripts since we removed the agenda logic block that used it

    // 3. Content Slides

    // 2. Content Slides
    const slidesStep = course.steps?.find(s =>
        s.title_key === 'course.steps.slides' ||
        s.title_key === 'livrables.slides' ||
        s.title_key.toLowerCase() === 'slides' ||
        s.title_key.toLowerCase().includes('.slides')
    ) || null;

    if (!slidesStep) {
        throw new Error('No Slides step found for PPTX export');
    }

    let hasSummarySlide = false;
    const blockingErrors: string[] = [];

    if (slidesStep.slides_data && Array.isArray(slidesStep.slides_data) && slidesStep.slides_data.length > 0) {
        console.log('[Export] Utilizing deterministic PPTX pipeline from stored slides_data');
        const slidesToExport: SlideState[] = slidesStep.slides_data;
        
        for (const slideState of slidesToExport) {
            // Skip cover/recap slides as they are handled globally or locally
            if (slideState.layoutId === 'LAYOUT_TITLE' && slideState.metadata.originalIndex === -1) {
                continue;
            }
            if (slideState.layoutId === 'LAYOUT_SUMMARY' && slideState.metadata.originalIndex === 9999) {
                continue;
            }

            const slide = pptx.addSlide();
            
            const mapLayout = (l: string): SlideDesignJSON['layout'] => {
                switch (l) {
                    case 'LAYOUT_TITLE': return 'HERO';
                    case 'LAYOUT_EXPLAINER': return 'DEFAULT';
                    case 'LAYOUT_IMAGE_TEXT': return 'DEFAULT';
                    case 'LAYOUT_IMAGE_LEFT': return 'SPLIT_LEFT';
                    case 'LAYOUT_IMAGE_RIGHT': return 'SPLIT_RIGHT';
                    case 'LAYOUT_FULL_IMAGE': return 'FULL_IMAGE';
                    case 'LAYOUT_QUOTE': return 'QUOTATION';
                    case 'LAYOUT_BIG_NUMBER': return 'BIG_STAT';
                    case 'LAYOUT_THREE_COL': return 'THREE_COLUMNS';
                    case 'LAYOUT_COMPARISON': return 'COMPARISON';
                    case 'LAYOUT_TIMELINE': return 'TIMELINE';
                    case 'LAYOUT_GRID_CARDS': return 'GRID_CARDS';
                    case 'LAYOUT_SECTION_HEADER': return 'SECTION_HEADER';
                    case 'LAYOUT_CHECKLIST': return 'CHECKLIST';
                    case 'LAYOUT_DO_DONT': return 'DO_DONT';
                    case 'LAYOUT_TABLE': return 'TABLE_SIMPLE';
                    case 'LAYOUT_IMAGE_CENTER': return 'IMAGE_CENTER';
                    case 'LAYOUT_EXERCISE': return 'PROCESS_STEPS';
                    case 'LAYOUT_AGENDA': return 'AGENDA_COMPACT';
                    default: return 'DEFAULT';
                }
            };

            const design: SlideDesignJSON = {
                title: slideState.content.title,
                layout: mapLayout(slideState.layoutId),
                content: slideState.content.bullets || [],
                columns: slideState.content.columns,
                bigValue: slideState.content.bigValue,
                bigLabel: slideState.content.bigLabel,
                quote: slideState.content.quote,
                table: slideState.content.table,
                imagePrompt: slideState.media?.caption || ''
            };

            let imageUrl = slideState.media?.url || '';
            if (imageUrl && !imageUrl.startsWith('data:')) {
                try {
                    const dataUrl = await fetchToDataUrl(imageUrl);
                    if (dataUrl) imageUrl = dataUrl;
                } catch (e) {
                    console.warn('Failed to fetch image for PPTX export:', e);
                }
            }

            switch (design.layout) {
                case 'HERO': renderHeroSlide(slide, design, imageUrl); break;
                case 'SPLIT_LEFT': renderSplitLeft(slide, design, imageUrl); break;
                case 'SPLIT_RIGHT': renderSplitRight(slide, design, imageUrl); break;
                case 'BIG_STAT': renderBigStat(slide, design, imageUrl); break;
                case 'COMPARISON': renderComparison(slide, design, imageUrl); break;
                case 'QUOTATION': renderQuotation(slide, design, imageUrl); break;
                case 'TIMELINE': renderTimeline(slide, design, imageUrl); break;
                case 'FULL_IMAGE': renderFullImage(slide, design, imageUrl); break;
                case 'GRID_CARDS': renderGridCards(slide, design, imageUrl); break;
                case 'IMAGE_CENTER': renderImageCenter(slide, design, imageUrl); break;
                case 'THREE_COLUMNS': renderThreeColumns(slide, design, imageUrl); break;
                case 'SECTION_HEADER': renderSectionHeader(slide, design, imageUrl); break;
                case 'CHECKLIST': renderChecklist(slide, design, imageUrl); break;
                case 'DO_DONT': renderDoDont(slide, design, imageUrl); break;
                case 'TABLE_SIMPLE': renderTableSimple(slide, design, imageUrl); break;
                case 'PROCESS_STEPS': renderProcessSteps(slide, design, imageUrl); break;
                case 'AGENDA_COMPACT': renderAgendaCompact(slide, design, imageUrl); break;
                default: renderDefault(slide, design, imageUrl);
            }

            if (slideState.speakerNotes) {
                const normalizedNotes = normalizeNotesText(slideState.speakerNotes);
                if (normalizedNotes) slide.addNotes(normalizedNotes);
            }

            slide.addText(`${course.title} | ${new Date().toLocaleDateString()}`, {
                x: 0.5, y: 6.8, w: '90%', h: 0.3,
                fontSize: 10, color: '9CA3AF', align: 'right'
            });
        }
    } else {
        const stepsToExport = [slidesStep];
        const MAX_CONCURRENCY = 3;

        for (const step of stepsToExport) {
            if (step.content) {
                const pre = normalizeExternalImageLinks(step.content);
                const withPublic = await replaceBlobUrlsWithPublic(pre, course.user_id, course.id);
                let contentForParsing = withPublic;
                if (looksLikeHtml(contentForParsing)) {
                    try {
                        const td = new TurndownService({ headingStyle: 'atx', codeBlockStyle: 'fenced' });
                        td.addRule('preserveComments', {
                            filter: (node: any) => node.nodeType === 8 && (
                                node.nodeValue?.trim().startsWith('slide-layout:') || 
                                node.nodeValue?.trim().startsWith('slide-adapted:')
                            ),
                            replacement: (_content: string, node: any) => {
                                return '<!--' + node.nodeValue + '-->';
                            }
                        });
                        contentForParsing = td.turndown(contentForParsing);
                    } catch {
                        contentForParsing = contentForParsing
                            .replace(/<br\s*\/?>/gi, '\n')
                            .replace(/<\/(p|div|section|article|li|h[1-6])>/gi, '\n')
                            .replace(/<[^>]+>/g, '');
                    }
                }
                const sections = parseContentSections(contentForParsing);

                for (let i = 0; i < sections.length; i += MAX_CONCURRENCY) {
                    const batch = sections.slice(i, i + MAX_CONCURRENCY);
                    
                    await Promise.all(batch.map(async (section) => {
                        const slide = pptx.addSlide();
                        let aiDesign: SlideDesignJSON = getSmartFallbackDesign(section.rawContent);
                        
                        if (section.slideLayout === SlideArchetype.Summary || section.title.toLowerCase().includes('summary') || section.title.toLowerCase().includes('rezumat')) {
                            hasSummarySlide = true;
                        }

                        if (section.slideLayout) {
                            const mapLayout = (a: SlideArchetype): SlideDesignJSON['layout'] => {
                                switch (a) {
                                    case SlideArchetype.Title: return 'HERO';
                                    case SlideArchetype.ImageLeft: return 'SPLIT_LEFT';
                                    case SlideArchetype.ImageRight: return 'SPLIT_RIGHT';
                                    case SlideArchetype.BigNumber: return 'BIG_STAT';
                                    case SlideArchetype.Comparison: return 'COMPARISON';
                                    case SlideArchetype.Quote: return 'QUOTATION';
                                    case SlideArchetype.Timeline: return 'TIMELINE';
                                    case SlideArchetype.FullImage: return 'FULL_IMAGE';
                                    case SlideArchetype.GridCards: return 'GRID_CARDS';
                                    case SlideArchetype.ImageCenter: return 'IMAGE_CENTER';
                                    case SlideArchetype.ThreeCol: return 'THREE_COLUMNS';
                                    case SlideArchetype.SectionHeader: return 'SECTION_HEADER';
                                    case SlideArchetype.Checklist: return 'CHECKLIST';
                                    case SlideArchetype.DoDont: return 'DO_DONT';
                                    case SlideArchetype.Table: return 'TABLE_SIMPLE';
                                    case SlideArchetype.Exercise: return 'PROCESS_STEPS';
                                    case SlideArchetype.Agenda: return 'AGENDA_COMPACT';
                                    case SlideArchetype.CaseStudy: return 'DEFAULT';
                                    case SlideArchetype.Summary: return 'DEFAULT';
                                    case SlideArchetype.Explainer: return 'DEFAULT';
                                    default: return 'DEFAULT';
                                }
                            };
                            aiDesign.layout = mapLayout(section.slideLayout);
                        }

                        let explicitContent = '';
                        if (aiDesign.layout && section.adaptedContent && section.adaptedContent[aiDesign.layout]) {
                            explicitContent = section.adaptedContent[aiDesign.layout];
                        } else if (section.adaptedContent && Object.keys(section.adaptedContent).length > 0) {
                            explicitContent = Object.values(section.adaptedContent)[0];
                        }

                        if (explicitContent) {
                            const plainText = explicitContent
                                .replace(/<br\s*\/?>/gi, '\n')
                                .replace(/<\/(p|div|li)>/gi, '\n')
                                .replace(/<[^>]+>/g, '')
                                .replace(/&nbsp;/g, ' ');
                            
                            aiDesign.content = plainText
                                .split('\n')
                                .map(s => s.trim())
                                .filter(Boolean);
                        } else {
                            if (section.bulletPoints.length > 0) {
                                aiDesign.content = section.bulletPoints;
                            } else if (section.bodyText) {
                                aiDesign.content = section.bodyText
                                .split('\n')
                                .map(s => s.trim())
                                .filter(Boolean);
                            } else {
                                aiDesign.content = [];
                            }
                        }

                        aiDesign.title = section.title;
                        aiDesign.imagePrompt = section.visualSearchTerm || '';

                        let imageUrl = '';
                        if (!isEnabled('pptxTextOnlySafeMode')) {
                            const finalPrompt = aiDesign.imagePrompt;
                            if (finalPrompt) {
                                try {
                                    const searchKeywords = finalPrompt.replace(/^(Photo of|Image of|Visual of)\s+/i, '').split(/[\s,]+/).slice(0, 4).join(' ');
                                    const searchPromise = searchImages(searchKeywords, 1);
                                    const timeoutPromise = new Promise<never>((_, reject) =>
                                        setTimeout(() => reject(new Error('Image Search Timeout')), 8000)
                                    );
                                    const images = await Promise.race([searchPromise, timeoutPromise]) as any[];
                                    if (images && images.length > 0) {
                                        imageUrl = images[0].url;
                                    }
                                } catch (e) {
                                    console.warn('Image search failed/timed out for slide:', section.title);
                                }
                            }
                            if (!imageUrl && section.images.length > 0) {
                                imageUrl = section.images[0].url;
                            }
                        }

                        if (imageUrl && !imageUrl.startsWith('data:')) {
                            try {
                                const dataUrl = await fetchToDataUrl(imageUrl);
                                if (dataUrl) {
                                    imageUrl = dataUrl;
                                } else {
                                    console.warn('Failed to convert image to Base64, removing to prevent corruption:', imageUrl);
                                    imageUrl = ''; 
                                }
                            } catch (e) {
                                 console.warn('Exception converting image to Base64:', e);
                                 imageUrl = '';
                            }
                        }

                        if (!aiDesign.layout) aiDesign.layout = 'DEFAULT';
                        const enumerativeLayouts = ['AGENDA_COMPACT','CHECKLIST','PROCESS_STEPS','TIMELINE','KEY_TAKEAWAYS'];
                        const allowSplit = false;
                        const splitArray = <T,>(arr: T[], size: number): T[][] => {
                            const out: T[][] = [];
                            for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
                            return out;
                        };
                        const defaultChunk = [aiDesign.content];
                        const chunks = (isEnabled('pptxEnhancedPipeline') && allowSplit && enumerativeLayouts.includes(aiDesign.layout))
                            ? splitArray(aiDesign.content, 6)
                            : defaultChunk;
                        
                        for (let ci = 0; ci < chunks.length; ci++) {
                            const chunkSlide = ci === 0 ? slide : pptx.addSlide();
                            if (isEnabled('pptxEnhancedPipeline')) {
                                const missing: string[] = [];
                                if (!section.title || section.title.trim().length === 0) missing.push('title');
                                
                                if (missing.length > 0) {
                                    blockingErrors.push(`[BLOCK] ${section.title || '(no title)'}: lipsesc câmpuri obligatorii → ${missing.join(', ')}`);
                                    return;
                                }
                            }
                            let designForChunk = { ...aiDesign, content: chunks[ci] };
                            const sem = validateSemantic(designForChunk, !!imageUrl);
                            if (!sem.ok) {
                                const rotated = pickCompatibleLayout(designForChunk.layout, sem.contentClass);
                                designForChunk = { ...designForChunk, layout: rotated };
                                const sem2 = validateSemantic(designForChunk, !!imageUrl);
                                if (!sem2.ok) {
                                    if (isEnabled('pptxEnhancedPipeline')) {
                                        console.warn(`[Export Warning] Slide invalid: ${section.title} → ${sem.errors.join('; ')}. Falling back to DEFAULT.`);
                                        designForChunk = { ...designForChunk, layout: 'DEFAULT' };
                                    }
                                }
                            }
                            try {
                                switch (designForChunk.layout) {
                                    case 'HERO': renderHeroSlide(chunkSlide, designForChunk, imageUrl); break;
                                    case 'SPLIT_LEFT': renderSplitLeft(chunkSlide, designForChunk, imageUrl); break;
                                    case 'SPLIT_RIGHT': renderSplitRight(chunkSlide, designForChunk, imageUrl); break;
                                    case 'BIG_STAT': renderBigStat(chunkSlide, designForChunk, imageUrl); break;
                                    case 'COMPARISON': renderComparison(chunkSlide, designForChunk, imageUrl); break;
                                    case 'QUOTATION': renderQuotation(chunkSlide, designForChunk, imageUrl); break;
                                    case 'TIMELINE': renderTimeline(chunkSlide, designForChunk, imageUrl); break;
                                    case 'FULL_IMAGE': renderFullImage(chunkSlide, designForChunk, imageUrl); break;
                                    case 'GRID_CARDS': renderGridCards(chunkSlide, designForChunk, imageUrl); break;
                                    case 'IMAGE_CENTER': renderImageCenter(chunkSlide, designForChunk, imageUrl); break;
                                    case 'THREE_COLUMNS': renderThreeColumns(chunkSlide, designForChunk, imageUrl); break;
                                    case 'SECTION_HEADER': renderSectionHeader(chunkSlide, designForChunk, imageUrl); break;
                                    case 'CHECKLIST': renderChecklist(chunkSlide, designForChunk, imageUrl); break;
                                    case 'DO_DONT': renderDoDont(chunkSlide, designForChunk, imageUrl); break;
                                    case 'TABLE_SIMPLE': renderTableSimple(chunkSlide, designForChunk, imageUrl); break;
                                    case 'PROCESS_STEPS': renderProcessSteps(chunkSlide, designForChunk, imageUrl); break;
                                    case 'AGENDA_COMPACT': renderAgendaCompact(chunkSlide, designForChunk, imageUrl); break;
                                    default: renderDefault(chunkSlide, designForChunk, imageUrl);
                                }

                            if (isEnabled('pptxEnhancedPipeline')) {
                                let notesAdded = false;
                                const modelNotes = (section.speakerNotes || '').trim();
                                const candidateNotes = modelNotes.length > 0
                                    ? modelNotes
                                    : (findMatchingScript(scripts, section.title) || '').trim();
                                if (candidateNotes.length > 0) {
                                    const normalized = normalizeNotesText(candidateNotes);
                                    if (normalized) {
                                        chunkSlide.addNotes(normalized);
                                        notesAdded = true;
                                    }
                                }
                                if (isEnabled('pptxEnhancedPipeline') && modelNotes.length > 0 && !notesAdded) {
                                    blockingErrors.push(`[BLOCK] ${section.title}: notes există în model dar nu au fost atașate.`);
                                }
                            }

                                chunkSlide.addText(`${course.title} | ${new Date().toLocaleDateString()}`, {
                                    x: 0.5, y: 6.8, w: '90%', h: 0.3,
                                    fontSize: 10, color: '9CA3AF', align: 'right'
                                });

                            } catch (renderErr) {
                                console.error('Error rendering slide:', renderErr);
                                if (isEnabled('pptxEnhancedPipeline')) {
    }

    // 4. Summary Slide
    if (isEnabled('pptxEnhancedPipeline') && blockingErrors.length > 0) {
        console.warn(`Export finalizat cu avertismente:\n${blockingErrors.join('\n')}`);
        // throw new Error(`Export oprit. Probleme:\n${blockingErrors.join('\n')}`);
    }
    if (!hasSummarySlide) {
        // addSummarySlide(pptx);
    }
    const fileName = `${course.title.replace(/[^a-z0-9]/gi, '_')}_AI.pptx`;
    await pptx.writeFile({ fileName });
};

export const exportCourseAsPptx = async (course: Course): Promise<void> => {
    // ALWAYS use V2 exporter (Design Studio pipeline)
    // We removed the fallback to legacy to prevent mixed slide styles and missing features (diacritics, layout)
    try {
        await exportCourseAsPptxV2(course);
    } catch (e) {
        console.error('[Export] V2 exporter CRITICAL FAILURE:', e);
        throw e; // Fail loud instead of falling back to broken legacy
    }
};

const linkSlideModelsToBlueprint = (course: Course, models: SlideModel[]): SlideModel[] => {
    const bp = course.blueprint;
    if (!bp || !Array.isArray(bp.modules)) return models;
    const byTitle: Record<string, { sectionId: string; objective: string }> = {};
    for (const m of bp.modules) {
        for (const s of m.sections || []) {
            const k = (s.title || '').toLowerCase().trim();
            if (!k) continue;
            byTitle[k] = { sectionId: s.id, objective: m.learning_objective };
        }
    }
    return models.map(mm => {
        const t = (mm.title || '').toLowerCase().trim();
        const link = byTitle[t];
        if (!link) return mm;
        const objective_links = Array.isArray(mm.objective_links) ? mm.objective_links : [];
        const nextObj = link.objective ? [link.objective] : objective_links;
        return { ...mm, section_id: link.sectionId, objective_links: nextObj };
    });
};

export const getSlideModelsForPreview = async (course: Course): Promise<SlideModel[]> => {
    // 1. Try to find explicit slide content (Source of Truth)
    // Prioritize 'livrables.slides'
    let slidesStep = course.steps?.find(s => s.title_key === 'livrables.slides');
    
    if (!slidesStep) {
        slidesStep = course.steps?.find(s => 
            s.title_key.toLowerCase().includes('slides')
        );
    }

    const videoScriptStep = findStepByKey(course, 'video_scripts');
    const scripts = videoScriptStep ? parseVideoScripts(videoScriptStep.content) : {};

    if (slidesStep && slidesStep.content && slidesStep.content.length > 50) {
        const contentWithPublic = await replaceBlobUrlsWithPublic(slidesStep.content, course.user_id, course.id);
        const contentAllPublic = await ensurePublicExternalImages(contentWithPublic, course.user_id, course.id);
        
        // Use our robust parser WITHOUT linking to blueprint to avoid "ghost" modules overriding explicit slides
        let models = buildSlideModelsFromContent(contentAllPublic, slidesStep.title_key, scripts);
        
        // Do NOT link to blueprint here. We want exactly what is in the editor.
        // models = linkSlideModelsToBlueprint(course, models); 
        
        return models;
    }
    
    // Fallback logic
    let models = buildSlideModelsFromCourse(course, scripts);
    models = linkSlideModelsToBlueprint(course, models);
    return models;
};

export const getPedagogicWarnings = (m: SlideModel): string[] => {
    const rules = getTemplateRules(m.slide_type);
    const warnings: string[] = [];
    const titleLen = (m.title || '').length;
    if (rules.maxTitleChars && titleLen > rules.maxTitleChars) warnings.push('[WARN] Titlu prea lung pentru arhetip');
    const bullets = m.bullets || [];
    if (rules.maxBullets && bullets.length > rules.maxBullets) warnings.push('[WARN] Prea multe bullets');
    const maxLen = rules.maxBulletLength ?? null;
    if (maxLen !== null && bullets.some(b => b.length > maxLen)) warnings.push('[WARN] Bullets prea lungi');

    const density = ((m.title || '').length) + bullets.reduce((acc, b) => acc + b.length, 0);
    if (density > 1000) warnings.push('[WARN] Conținut prea dens pentru un singur slide');

    if (m.slide_type === SlideArchetype.ImageText && !m.image_url) warnings.push('[CRITICAL] Lipsește imaginea la Image+Text');

    const textAll = ((m.title || '') + ' ' + bullets.join(' ')).toLowerCase();
    const BLOOM = {
        remember: ['definește', 'defini', 'enumeră', 'listează', 'identifică', 'recunoaște', 'descrie', 'menționează'],
        understand: ['explică', 'interpretează', 'clarifică', 'rezumă', 'exemplifică', 'parafrazează', 'ilustrează'],
        apply: ['aplică', 'utilizează', 'folosește', 'implementează', 'exersează', 'execută', 'proiectează', 'realizează'],
        analyze: ['analizează', 'compară', 'descompune', 'relatează', 'examinează', 'categorizează', 'corelează'],
        evaluate: ['evaluează', 'argumentează', 'justifică', 'critică', 'decide', 'apreciază', 'verifică'],
        create: ['creează', 'sintetizează', 'compune', 'inovează', 'construiește', 'elaborează', 'proiectează']
    } as const;
    const bloomOrder = ['remember', 'understand', 'apply', 'analyze', 'evaluate', 'create'] as const;
    const detectBloomLevel = (t: string): number => {
        for (let i = bloomOrder.length - 1; i >= 0; i--) {
            const level = bloomOrder[i];
            const verbs = BLOOM[level];
            if (verbs.some(v => t.includes(v))) return i;
        }
        return -1;
    };
    const minLevelForArchetype = (a: SlideArchetype): number => {
        if (a === SlideArchetype.Exercise) return bloomOrder.indexOf('apply');
        if (a === SlideArchetype.CaseStudy) return bloomOrder.indexOf('analyze');
        if (a === SlideArchetype.Summary) return bloomOrder.indexOf('understand');
        if (a === SlideArchetype.Explainer) return bloomOrder.indexOf('understand');
        if (a === SlideArchetype.ImageText) return bloomOrder.indexOf('understand');
        return bloomOrder.indexOf('remember');
    };
    const bloomDetected = detectBloomLevel(textAll);
    const bloomRequired = minLevelForArchetype(m.slide_type);
    if (bloomDetected >= 0 && bloomDetected < bloomRequired) warnings.push('[WARN] Nivel Bloom prea scăzut pentru arhetip');

    if (m.slide_type === SlideArchetype.Exercise) {
        if (bullets.length < 3) warnings.push('[CRITICAL] Exercițiu fără pași suficienți');
        const hasApply = BLOOM.apply.some(v => textAll.includes(v));
        if (!hasApply) warnings.push('[WARN] Exercițiul ar trebui să ceară aplicare');
    }

    if (m.slide_type === SlideArchetype.CaseStudy) {
        const keys = ['context', 'problemă', 'soluție', 'rezultat'];
        const hits = keys.filter(k => textAll.includes(k)).length;
        if (hits < 2) warnings.push('[WARN] Studiu de caz fără structură clară');
        const hasEvaluate = BLOOM.evaluate.some(v => textAll.includes(v));
        if (!hasEvaluate) warnings.push('[INFO] Adaugă evaluare/concluzii pentru un studiu de caz robust');
    }

    if (m.slide_type === SlideArchetype.Summary) {
        const integrationHints = ['reflectă', 'plan', 'transfer', 'integrează', 'recapitulare', 'reține'];
        const hasIntegration = integrationHints.some(v => textAll.includes(v));
        if (!hasIntegration) warnings.push('[INFO] Îndeamnă la reflecție/plan de acțiune în rezumat');
    }

    return warnings;
};

const splitSentences = (text: string): string[] => {
    const clean = text.replace(/\s+/g, ' ').trim();
    if (!clean) return [];
    const parts = clean.split(/(?<=[.!?])\s+/);
    return parts.map(p => p.replace(/^[*•-]\s*/, '').trim()).filter(Boolean);
};

const deriveBulletsFromBody = (body: string): string[] => {
    const sents = splitSentences(body);
    return sents.slice(0, 6);
};

// V2 exporter: builds SlideModel IR and renders archetypes deterministically
const buildSlideModelsFromCourse = (course: Course, scripts: Record<string, string>): SlideModel[] => {
    const models: SlideModel[] = [];
    const steps = course.steps || [];
    for (const step of steps) {
        if (shouldExcludeFromSlides(step) || !step.content) continue;
        const sections = parseContentSections(step.content);
        sections.forEach((s, idx) => {
            const id = `${step.id}_sec_${idx + 1}`;
            const baseBullets = s.bulletPoints.length > 0 ? s.bulletPoints : deriveBulletsFromBody(s.bodyText || '');
            const image = s.images[0]?.url || null;
            const archetype = chooseArchetypeFor(step.title_key, s.title, image);
            const rules = getTemplateRules(archetype);
            let m: SlideModel = {
                id,
                slide_type: archetype,
                title: s.title,
                bullets: baseBullets,
                image_url: image,
                section_id: undefined,
                objective_links: [],
                trainer_notes: null,
            };
            m = normalizeSlide(m, rules);
            const note = findMatchingScript(scripts, s.title);
            if (note) m.trainer_notes = note;
            const valid = validateSlide(m, rules);
            if (!valid) {
                const fallbackRules = getTemplateRules(SlideArchetype.Explainer);
                m.slide_type = SlideArchetype.Explainer;
                m = normalizeSlide(m, fallbackRules);
            }
            models.push(m);
        });
    }
    return models;
};


export const formatToCanonicalSlides = (markdown: string, language: string = 'en'): string => {
    // Clean wrappers first (fix for XML/Markdown code blocks)
    let cleaned = markdown;
    // Remove ```xml, ```markdown, or ``` wrappers if present at start/end
    cleaned = cleaned
        .replace(/^\s*```(?:xml|html|markdown|text)?\s*[\r\n]+/, '')
        .replace(/[\r\n]+\s*```\s*$/, '');

    const keywords = getParsingKeywords(language);
    const slideIdentifierPattern = keywords.slideIdentifier.join('|');
    const primarySlideId = keywords.slideIdentifier[0] || 'Slide';

    // If content already has explicit "Slide N:" markers, respect existing authoring and return as-is
    const hasExplicitSlidesRegex = new RegExp(`\\b(${slideIdentifierPattern})\\s*\\d+\\s*:`, 'i');
    const hasExplicitSlides = hasExplicitSlidesRegex.test(cleaned || '');
    if (hasExplicitSlides) {
        return cleaned;
    }
    const sections = parseContentSections(cleaned, language);
    const lines: string[] = [];
    sections.forEach((s, idx) => {
        const n = idx + 1;
        const title = s.title || `${primarySlideId} ${n}`;
        lines.push(`${primarySlideId} ${n}: ${title}`);
        const layoutEnum = s.slideLayout ?? (s.images[0]?.url ? SlideArchetype.ImageText : SlideArchetype.Explainer);
        lines.push(`<!-- slide-layout: ${layoutEnum} -->`);
        const adaptedForActive = s.adaptedContent?.[layoutEnum];
        if (typeof adaptedForActive === 'string' && adaptedForActive.trim().length > 0) {
            lines.push(`<!-- slide-adapted: ${layoutEnum} | ${adaptedForActive.trim()} -->`);
        }
        if (s.visualSearchTerm && s.visualSearchTerm.trim()) {
            lines.push(`Visual: ${s.visualSearchTerm.trim()}`);
        }
        lines.push('Text:');
        const bullets = s.bulletPoints.length > 0 ? s.bulletPoints : deriveBulletsFromBody(s.bodyText || '');
        bullets.forEach(b => lines.push(`- ${b}`));
        if (s.images.length > 0) {
            const img = s.images[0];
            lines.push(`![${img.alt || ''}](${img.url})`);
        }
        if (s.speakerNotes && s.speakerNotes.trim()) {
            lines.push(`Speaker Notes: ${s.speakerNotes.trim()}`);
        }
        lines.push('---');
        lines.push('');
    });
    return lines.join('\n').trim();
};

const buildSlideModelsFromContent = (markdown: string, titleKey: string, scripts: Record<string, string>): SlideModel[] => {
    const models: SlideModel[] = [];
    const sections = parseContentSections(markdown);
    sections.forEach((s, idx) => {
        const id = `${titleKey}_sec_${idx + 1}`;
        const image = s.images[0]?.url || null;
        const archetype = s.slideLayout ?? chooseArchetypeFor(titleKey, s.title, image);
        const rules = getTemplateRules(archetype);
        let m: SlideModel = {
            id,
            originalIndex: idx,
            slide_type: archetype,
            title: s.title,
            bullets: s.bulletPoints.length > 0 ? s.bulletPoints : (s.bodyText ? s.bodyText.split('\n') : []),
            image_url: image,
            image_prompt: s.visualSearchTerm,
            section_id: undefined,
            objective_links: [],
            trainer_notes: s.speakerNotes || null,
            adaptedContent: s.adaptedContent
        };
        m = normalizeSlide(m, rules);
        const note = findMatchingScript(scripts, s.title);
        if (note && !m.trainer_notes) m.trainer_notes = note; // Only use script if no specific notes found
        const valid = validateSlide(m, rules);
        if (!valid) {
            const fallbackRules = getTemplateRules(SlideArchetype.Explainer);
            m.slide_type = SlideArchetype.Explainer;
            m = normalizeSlide(m, fallbackRules);
        }
        models.push(m);
    });
    return models;
};



const TEMPLATE_RULES: Record<SlideArchetype, SlideRules> = {
    [SlideArchetype.Title]: { maxTitleChars: 60 },
    [SlideArchetype.Explainer]: { maxTitleChars: 60, maxBullets: 5, maxBulletLength: 110 },
    [SlideArchetype.ImageText]: { maxTitleChars: 60, maxBullets: 4, maxBulletLength: 100, requiresImage: true },
    [SlideArchetype.ImageLeft]: { maxTitleChars: 60, maxBullets: 5, maxBulletLength: 100, requiresImage: true },
    [SlideArchetype.ImageRight]: { maxTitleChars: 60, maxBullets: 5, maxBulletLength: 100, requiresImage: true },
    [SlideArchetype.FullImage]: { maxTitleChars: 60, requiresImage: true },
    [SlideArchetype.Quote]: { maxTitleChars: 120 },
    [SlideArchetype.BigNumber]: { maxTitleChars: 40, maxBullets: 2, maxBulletLength: 60 },
    [SlideArchetype.ThreeCol]: { maxTitleChars: 80, maxBullets: 9, maxBulletLength: 60 },
    [SlideArchetype.Comparison]: { maxTitleChars: 60, maxBullets: 8, maxBulletLength: 80 },
    [SlideArchetype.Timeline]: { maxTitleChars: 60, maxBullets: 5, maxBulletLength: 100 },
    [SlideArchetype.GridCards]: { maxTitleChars: 60, maxBullets: 6, maxBulletLength: 80 },
    [SlideArchetype.SectionHeader]: { maxTitleChars: 80 },
    [SlideArchetype.Checklist]: { maxTitleChars: 60, maxBullets: 8, maxBulletLength: 100 },
    [SlideArchetype.DoDont]: { maxTitleChars: 60, maxBullets: 8, maxBulletLength: 100 },
    [SlideArchetype.Table]: { maxTitleChars: 60, maxBullets: 10, maxBulletLength: 80 },
    [SlideArchetype.ImageCenter]: { maxTitleChars: 60, maxBullets: 3, maxBulletLength: 100, requiresImage: true },
    [SlideArchetype.Agenda]: { maxBullets: 8, maxBulletLength: 80 },
    [SlideArchetype.Exercise]: { maxTitleChars: 80, maxBullets: 6, maxBulletLength: 120 },
    [SlideArchetype.CaseStudy]: { maxTitleChars: 80, maxBullets: 5, maxBulletLength: 120 },
    [SlideArchetype.Summary]: { maxBullets: 5, maxBulletLength: 80 },
};

export const getTemplateRules = (a: SlideArchetype): SlideRules => TEMPLATE_RULES[a] || { maxTitleChars: 60 };

const trimTo = (s: string, n: number): string => (s.length > n ? (s.slice(0, Math.max(0, n - 3)) + '…') : s);

export const normalizeSlide = (m: SlideModel, r: SlideRules): SlideModel => {
    const title = m.title ? (r.maxTitleChars ? trimTo(m.title, r.maxTitleChars) : m.title) : m.title;
    const maxB = typeof r.maxBullets === 'number' ? r.maxBullets : undefined;
    const clipBullets = (m.bullets || []).slice(0, maxB || (m.bullets || []).length).map(b => {
        const lim = r.maxBulletLength || 9999;
        return trimTo(b, lim);
    });
    const image = r.requiresImage ? (m.image_url || null) : (m.image_url || null);
    return { ...m, title, bullets: clipBullets, image_url: image };
};

export const validateSlide = (m: SlideModel, r: SlideRules): boolean => {
    if (r.maxTitleChars && (m.title || '').length > r.maxTitleChars) return false;
    if (r.maxBullets && (m.bullets || []).length > r.maxBullets) return false;
    const maxLen = r.maxBulletLength ?? null;
    if (maxLen !== null && (m.bullets || []).some(b => b.length > maxLen)) return false;
    if (r.requiresImage && !m.image_url) return false;
    const density = ((m.title || '').length) + (m.bullets || []).reduce((acc, b) => acc + b.length, 0);
    if (density > 1200) return false;
    return true;
};

export const chooseArchetypeFor = (titleKey: string, sectionTitle: string, imageUrl: string | null): SlideArchetype => {
    const tk = titleKey.toLowerCase();
    const st = sectionTitle.toLowerCase();
    if (tk.includes('exercise') || st.includes('exerci')) return SlideArchetype.Exercise;
    if (tk.includes('case') || st.includes('studiu')) return SlideArchetype.CaseStudy;
    if (tk.includes('summary') || tk.includes('recap') || st.includes('rezumat')) return SlideArchetype.Summary;
    if (tk.includes('quote') || st.includes('citat')) return SlideArchetype.Quote;
    if (imageUrl) return SlideArchetype.ImageText;
    return SlideArchetype.Explainer;
};

// ============================================================================
// LEGACY EXPORTS
// ============================================================================

const normalizeMarkdownImages = (md: string): string => md.replace(/!\[([^\]]*)\]\s*\n\s*\(([^)]+)\)/g, '![$1]($2)');

const base64ToUint8Array = (base64: string): Uint8Array => {
    const binary = atob(base64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return bytes;
};

const fetchImageBytes = async (url: string): Promise<Uint8Array | null> => {
    try {
        if (url.startsWith('data:')) {
            const payload = url.split('base64,')[1] || '';
            if (!payload) return null;
            return base64ToUint8Array(payload);
        }
        const res = await fetch(url);
        if (!res.ok) return null;
        const buf = await res.arrayBuffer();
        return new Uint8Array(buf);
    } catch {
        return null;
    }
};

const parseTextToRuns = (text: string): TextRun[] => {
    const runs: TextRun[] = [];
    const parts = text.split(/(\*\*.*?\*\*)/g);
    parts.forEach(part => {
        if (part.startsWith('**') && part.endsWith('**')) {
            runs.push(new TextRun({ text: part.slice(2, -2), bold: true }));
        } else if (part) {
            runs.push(new TextRun(part));
        }
    });
    return runs;
};

const createDocxTable = (lines: string[]): Table | null => {
    try {
        const rows = lines.map(line => {
            const content = line.trim().replace(/^\|/, '').replace(/\|$/, '');
            return content.split('|').map(c => c.trim());
        });

        if (rows.length < 2) return null;

        const headers = rows[0];
        const dataRows = rows.slice(2); // Skip separator row

        const tableRows: TableRow[] = [];

        // Header
        tableRows.push(new TableRow({
            tableHeader: true,
            children: headers.map(h => new TableCell({
                children: [new Paragraph({
                    children: [new TextRun({ text: h, bold: true })],
                    alignment: AlignmentType.CENTER
                })],
                shading: { fill: "F3F4F6" },
                verticalAlign: "center",
                borders: {
                    top: { style: BorderStyle.SINGLE, size: 1, color: "000000" },
                    bottom: { style: BorderStyle.SINGLE, size: 1, color: "000000" },
                    left: { style: BorderStyle.SINGLE, size: 1, color: "000000" },
                    right: { style: BorderStyle.SINGLE, size: 1, color: "000000" },
                }
            }))
        }));

        // Body
        dataRows.forEach(row => {
            const cells = row.map(cellText => new TableCell({
                children: [new Paragraph({ children: parseTextToRuns(cellText) })],
                borders: {
                    top: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
                    bottom: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
                    left: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
                    right: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
                }
            }));
            tableRows.push(new TableRow({ children: cells }));
        });

        return new Table({
            rows: tableRows,
            width: { size: 100, type: WidthType.PERCENTAGE },
        });
    } catch (e) {
        console.warn('Failed to parse table:', e);
        return null;
    }
};

const buildDocxParagraphs = async (content: string): Promise<(Paragraph | Table)[]> => {
    const children: (Paragraph | Table)[] = [];
    const lines = normalizeMarkdownImages(content).split('\n');
    const imageRegex = /!\[([^\]]*)\]\(([^)]+)\)/;

    let i = 0;
    while (i < lines.length) {
        const line = lines[i];
        const trimmed = line.trim();

        // Detect Table
        if (trimmed.startsWith('|') && i + 1 < lines.length) {
            const nextLine = lines[i + 1].trim();
            if (nextLine.startsWith('|') && nextLine.includes('---')) {
                const tableLines: string[] = [];
                while (i < lines.length && lines[i].trim().startsWith('|')) {
                    tableLines.push(lines[i]);
                    i++;
                }
                const table = createDocxTable(tableLines);
                if (table) {
                    children.push(table);
                } else {
                    tableLines.forEach(l => children.push(new Paragraph({ text: l })));
                }
                continue;
            }
        }

        const match = line.match(imageRegex);
        if (match) {
            const alt = match[1] || '';
            const url = match[2];
            const bytes = await fetchImageBytes(url);
            if (bytes) {
                children.push(new Paragraph({ children: [new ImageRun({ data: bytes, transformation: { width: 480, height: 360 } })] }));
            } else {
                children.push(new Paragraph({ children: [new TextRun(`Image: ${alt}`)] }));
            }
            i++;
            continue;
        }

        if (line.startsWith('# ')) {
            children.push(new Paragraph({ text: line.substring(2), heading: HeadingLevel.HEADING_1, alignment: AlignmentType.CENTER }));
        } else if (line.startsWith('## ')) {
            children.push(new Paragraph({ text: line.substring(3), heading: HeadingLevel.HEADING_2 }));
        } else if (line.startsWith('### ')) {
            children.push(new Paragraph({ text: line.substring(4), heading: HeadingLevel.HEADING_3 }));
        } else if (line.startsWith('* ') || line.startsWith('- ')) {
            children.push(new Paragraph({ text: line.substring(2), bullet: { level: 0 } }));
        } else if (trimmed === '') {
            children.push(new Paragraph({ text: '' }));
        } else {
            children.push(new Paragraph({ children: parseTextToRuns(line) }));
        }
        i++;
    }
    return children;
};

const createDocx = async (step: CourseStep, courseTitle: string, stepTitle: string): Promise<Blob> => {
    const pre = normalizeExternalImageLinks(step.content);
    const withPublic = await replaceBlobUrlsWithPublic(pre, step.user_id || null, step.course_id || null);

    let normalizedForDocx = withPublic;

    // Dacă pasul conține tabele HTML (ex. copiate din Excel), convertim HTML-ul la Markdown GFM
    // astfel încât pipeline-ul de DOCX (buildDocxParagraphs + createDocxTable) să le poată reda ca tabele Word.
    if (/<table[\s>]/i.test(normalizedForDocx)) {
        try {
            const turndownModule: any = await import('turndown');
            const TurndownService = turndownModule.default || turndownModule;
            const turndownPluginGfm: any = await import('turndown-plugin-gfm');
            const gfm = turndownPluginGfm.gfm || turndownPluginGfm;

            const td = new TurndownService({ headingStyle: 'atx', codeBlockStyle: 'fenced' });
            td.keep(['img']);
            td.use(gfm);

            normalizedForDocx = td.turndown(normalizedForDocx);
        } catch (e) {
            console.warn('[Export] Failed to normalize HTML tables to Markdown for DOCX export:', e);
        }
    }

    const children = await buildDocxParagraphs(normalizedForDocx);
    const doc = new Document({
        sections: [{
            headers: {
                default: new Header({
                    children: [
                        new Paragraph({
                            children: [
                                new TextRun({ text: `${courseTitle} - ${stepTitle}`, size: 18, color: "888888" }),
                            ],
                            alignment: AlignmentType.RIGHT,
                        }),
                    ]
                }),
            },
            children,
        }],
    });
    return Packer.toBlob(doc);
};

export const exportCourseAsZip = async (course: Course, t: (key: string) => string): Promise<void> => {
    console.log('[Export] Starting zip export for:', course.title);
    const zip = new JSZip();

    for (const step of course.steps || []) {
        const stepTitle = t(step.title_key).replace(/^\d+\.\s*/, '');
        const blob = await createDocx(step, course.title, stepTitle);
        const fileName = `${stepTitle}.docx`;
        zip.file(fileName, blob);
    }

    // Generate ZIP with proper MIME type
    const zipBlob = await zip.generateAsync({
        type: 'blob',
        mimeType: 'application/zip'
    });

    const safeCourseTitle = course.title.replace(/[^a-z0-9]/gi, '_');
    const finalFileName = `course_${safeCourseTitle}.zip`;

    console.log('[Export] Zip generated, triggering download for:', finalFileName);

    // Trigger download using standard approach
    const url = URL.createObjectURL(zipBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = finalFileName;
    link.style.display = 'none';
    document.body.appendChild(link);
    link.click();

    // Cleanup
    setTimeout(() => {
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }, 100);
};

// Re-export PDF export function
export { exportCourseAsPdf };

export const exportSlidesAsPptx = async (course: Course, slides: SlideState[]): Promise<void> => {
    const pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_16x9';
    pptx.author = 'AI Course Co-Pilot';
    pptx.company = 'Course Copilot';
    pptx.title = course.title;

    for (const slide of slides) {
        const pptxSlide = pptx.addSlide();
        
        // Prepare image
        let imageUrl = slide.media?.url || '';
        if (imageUrl && !imageUrl.startsWith('data:')) {
             try {
                 const dataUrl = await fetchToDataUrl(imageUrl);
                 if (dataUrl) imageUrl = dataUrl;
             } catch (e) {
                 console.warn('Failed to fetch image for slide', slide.id, e);
             }
        }
        
        // Construct SlideDesignJSON
        const designData: SlideDesignJSON = {
            layout: 'DEFAULT', 
            title: slide.content.title,
            content: slide.content.bullets,
            imagePrompt: '',
            accentColor: '1E3A8A'
        };
        
        if (slide.content.subtitle) {
            designData.content = [slide.content.subtitle, ...slide.content.bullets];
        }

        // Switch on layoutId
        switch (slide.layoutId) {
            case 'LAYOUT_TITLE':
                renderHeroSlide(pptxSlide, designData, imageUrl);
                break;
            case 'LAYOUT_EXPLAINER':
                renderSplitLeft(pptxSlide, designData, imageUrl);
                break;
            case 'LAYOUT_IMAGE_TEXT':
                renderSplitRight(pptxSlide, designData, imageUrl);
                break;
            case 'LAYOUT_IMAGE_LEFT':
                renderSplitLeft(pptxSlide, designData, imageUrl);
                break;
            case 'LAYOUT_IMAGE_RIGHT':
                renderSplitRight(pptxSlide, designData, imageUrl);
                break;
            case 'LAYOUT_FULL_IMAGE':
                renderFullImage(pptxSlide, designData, imageUrl);
                break;
            case 'LAYOUT_QUOTE':
                if (slide.content.quote) {
                    designData.content = [slide.content.quote.text, slide.content.quote.author];
                }
                renderQuotation(pptxSlide, designData, imageUrl);
                break;
            case 'LAYOUT_BIG_NUMBER':
                 if (slide.content.bigValue) {
                     designData.content = [slide.content.bigValue, slide.content.bigLabel || ''];
                 }
                 renderBigStat(pptxSlide, designData, imageUrl);
                 break;
            case 'LAYOUT_THREE_COL':
                 if (slide.content.columns) {
                     designData.content = slide.content.columns.flatMap(c => [c.header || '', ...(c.content || [])]);
                 }
                 renderThreeColumns(pptxSlide, designData, imageUrl);
                 break;
            case 'LAYOUT_COMPARISON':
                 if (slide.content.columns) {
                    designData.content = slide.content.columns.flatMap(c => [c.header || '', ...(c.content || [])]);
                 }
                 renderComparison(pptxSlide, designData, imageUrl);
                 break;
            case 'LAYOUT_TIMELINE':
                 renderTimeline(pptxSlide, designData, imageUrl);
                 break;
            case 'LAYOUT_GRID_CARDS':
                 renderGridCards(pptxSlide, designData, imageUrl);
                 break;
            case 'LAYOUT_SECTION_HEADER':
                 renderSectionHeader(pptxSlide, designData, imageUrl);
                 break;
            case 'LAYOUT_CHECKLIST':
                 renderChecklist(pptxSlide, designData, imageUrl);
                 break;
            case 'LAYOUT_DO_DONT':
                 renderDoDont(pptxSlide, designData, imageUrl);
                 break;
            case 'LAYOUT_TABLE':
                 renderTableSimple(pptxSlide, designData, imageUrl);
                 break;
            case 'LAYOUT_IMAGE_CENTER':
                 renderImageCenter(pptxSlide, designData, imageUrl);
                 break;
            case 'LAYOUT_EXERCISE':
                 renderProcessSteps(pptxSlide, designData, imageUrl); 
                 break;
            case 'LAYOUT_AGENDA':
                 renderAgendaCompact(pptxSlide, designData, imageUrl);
                 break;
            case 'LAYOUT_SUMMARY':
                 // Use GridCards for summary to match Design Studio look, and respect the original title
                 renderGridCards(pptxSlide, designData, imageUrl);
                 break;
            case 'LAYOUT_CASE_STUDY':
                 renderSplitRight(pptxSlide, designData, imageUrl);
                 break;
            default:
                renderDefault(pptxSlide, designData, imageUrl);
        }
    }
    
    const fileName = `${course.title.replace(/[^a-z0-9]/gi, '_')}_Visual.pptx`;
    await pptx.writeFile({ fileName });
};

// Debug/testing export for parser
export { parseContentSections as __debugParseContentSections };
