// Source of Truth for Slide Layout Tokens
// Used by Parser, Markdown Injection, and UI Dropdowns
// This ensures tight coupling between what the UI writes and what the parser reads.

import { SlideArchetype } from '../types';

// The Token Constants (what is written in Markdown comments)
export const SLIDE_LAYOUT_TOKENS = {
  TITLE: 'TITLE',
  HERO: 'HERO',
  EXPLAINER: 'EXPLAINER',
  IMAGE_TEXT: 'IMAGE_TEXT',
  IMAGE_LEFT: 'IMAGE_LEFT',
  SPLIT_LEFT: 'SPLIT_LEFT',
  IMAGE_RIGHT: 'IMAGE_RIGHT',
  SPLIT_RIGHT: 'SPLIT_RIGHT',
  FULL_IMAGE: 'FULL_IMAGE',
  QUOTE: 'QUOTE',
  QUOTATION: 'QUOTATION',
  QUOTE_CENTER: 'QUOTE_CENTER',
  BIG_NUMBER: 'BIG_NUMBER',
  BIG_STAT: 'BIG_STAT',
  THREE_COL: 'THREE_COL',
  THREE_COLUMNS: 'THREE_COLUMNS',
  COMPARISON: 'COMPARISON',
  TIMELINE: 'TIMELINE',
  GRID_CARDS: 'GRID_CARDS',
  SECTION_HEADER: 'SECTION_HEADER',
  CHECKLIST: 'CHECKLIST',
  DO_DONT: 'DO_DONT',
  TABLE: 'TABLE',
  TABLE_SIMPLE: 'TABLE_SIMPLE',
  IMAGE_CENTER: 'IMAGE_CENTER',
  EXERCISE: 'EXERCISE',
  PROCESS_STEPS: 'PROCESS_STEPS',
  AGENDA: 'AGENDA',
  AGENDA_COMPACT: 'AGENDA_COMPACT',
  SUMMARY: 'SUMMARY',
  KEY_TAKEAWAYS: 'KEY_TAKEAWAYS',
  CASE_STUDY: 'CASE_STUDY',
} as const;

// The Mapping (Token -> Internal Enum)
export const LAYOUT_TOKEN_MAPPING: Record<string, SlideArchetype> = {
  [SLIDE_LAYOUT_TOKENS.TITLE]: SlideArchetype.Title,
  [SLIDE_LAYOUT_TOKENS.HERO]: SlideArchetype.Title,
  [SLIDE_LAYOUT_TOKENS.EXPLAINER]: SlideArchetype.Explainer,
  [SLIDE_LAYOUT_TOKENS.IMAGE_TEXT]: SlideArchetype.ImageText,
  [SLIDE_LAYOUT_TOKENS.IMAGE_LEFT]: SlideArchetype.ImageLeft,
  [SLIDE_LAYOUT_TOKENS.SPLIT_LEFT]: SlideArchetype.ImageLeft,
  [SLIDE_LAYOUT_TOKENS.IMAGE_RIGHT]: SlideArchetype.ImageRight,
  [SLIDE_LAYOUT_TOKENS.SPLIT_RIGHT]: SlideArchetype.ImageRight,
  [SLIDE_LAYOUT_TOKENS.FULL_IMAGE]: SlideArchetype.FullImage,
  [SLIDE_LAYOUT_TOKENS.QUOTE]: SlideArchetype.Quote,
  [SLIDE_LAYOUT_TOKENS.QUOTATION]: SlideArchetype.Quote,
  [SLIDE_LAYOUT_TOKENS.QUOTE_CENTER]: SlideArchetype.Quote,
  [SLIDE_LAYOUT_TOKENS.BIG_NUMBER]: SlideArchetype.BigNumber,
  [SLIDE_LAYOUT_TOKENS.BIG_STAT]: SlideArchetype.BigNumber,
  [SLIDE_LAYOUT_TOKENS.THREE_COL]: SlideArchetype.ThreeCol,
  [SLIDE_LAYOUT_TOKENS.THREE_COLUMNS]: SlideArchetype.ThreeCol,
  [SLIDE_LAYOUT_TOKENS.COMPARISON]: SlideArchetype.Comparison,
  [SLIDE_LAYOUT_TOKENS.TIMELINE]: SlideArchetype.Timeline,
  [SLIDE_LAYOUT_TOKENS.GRID_CARDS]: SlideArchetype.GridCards,
  [SLIDE_LAYOUT_TOKENS.SECTION_HEADER]: SlideArchetype.SectionHeader,
  [SLIDE_LAYOUT_TOKENS.CHECKLIST]: SlideArchetype.Checklist,
  [SLIDE_LAYOUT_TOKENS.DO_DONT]: SlideArchetype.DoDont,
  [SLIDE_LAYOUT_TOKENS.TABLE]: SlideArchetype.Table,
  [SLIDE_LAYOUT_TOKENS.TABLE_SIMPLE]: SlideArchetype.Table,
  [SLIDE_LAYOUT_TOKENS.IMAGE_CENTER]: SlideArchetype.ImageCenter,
  [SLIDE_LAYOUT_TOKENS.EXERCISE]: SlideArchetype.Exercise,
  [SLIDE_LAYOUT_TOKENS.PROCESS_STEPS]: SlideArchetype.Exercise,
  [SLIDE_LAYOUT_TOKENS.AGENDA]: SlideArchetype.Agenda,
  [SLIDE_LAYOUT_TOKENS.AGENDA_COMPACT]: SlideArchetype.Agenda,
  [SLIDE_LAYOUT_TOKENS.SUMMARY]: SlideArchetype.Summary,
  [SLIDE_LAYOUT_TOKENS.KEY_TAKEAWAYS]: SlideArchetype.Summary,
  [SLIDE_LAYOUT_TOKENS.CASE_STUDY]: SlideArchetype.CaseStudy,
};

// Reverse Mapping (Enum -> Preferred Token for Writing)
export const ARCHETYPE_TO_TOKEN: Record<SlideArchetype, string> = {
  [SlideArchetype.Title]: SLIDE_LAYOUT_TOKENS.TITLE,
  [SlideArchetype.Explainer]: SLIDE_LAYOUT_TOKENS.EXPLAINER,
  [SlideArchetype.ImageText]: SLIDE_LAYOUT_TOKENS.IMAGE_TEXT,
  [SlideArchetype.ImageLeft]: SLIDE_LAYOUT_TOKENS.IMAGE_LEFT,
  [SlideArchetype.ImageRight]: SLIDE_LAYOUT_TOKENS.IMAGE_RIGHT,
  [SlideArchetype.FullImage]: SLIDE_LAYOUT_TOKENS.FULL_IMAGE,
  [SlideArchetype.Quote]: SLIDE_LAYOUT_TOKENS.QUOTE,
  [SlideArchetype.BigNumber]: SLIDE_LAYOUT_TOKENS.BIG_NUMBER,
  [SlideArchetype.ThreeCol]: SLIDE_LAYOUT_TOKENS.THREE_COL,
  [SlideArchetype.Comparison]: SLIDE_LAYOUT_TOKENS.COMPARISON,
  [SlideArchetype.Timeline]: SLIDE_LAYOUT_TOKENS.TIMELINE,
  [SlideArchetype.GridCards]: SLIDE_LAYOUT_TOKENS.GRID_CARDS,
  [SlideArchetype.SectionHeader]: SLIDE_LAYOUT_TOKENS.SECTION_HEADER,
  [SlideArchetype.Checklist]: SLIDE_LAYOUT_TOKENS.CHECKLIST,
  [SlideArchetype.DoDont]: SLIDE_LAYOUT_TOKENS.DO_DONT,
  [SlideArchetype.Table]: SLIDE_LAYOUT_TOKENS.TABLE,
  [SlideArchetype.ImageCenter]: SLIDE_LAYOUT_TOKENS.IMAGE_CENTER,
  [SlideArchetype.Exercise]: SLIDE_LAYOUT_TOKENS.EXERCISE,
  [SlideArchetype.Agenda]: SLIDE_LAYOUT_TOKENS.AGENDA,
  [SlideArchetype.Summary]: SLIDE_LAYOUT_TOKENS.SUMMARY,
  [SlideArchetype.CaseStudy]: SLIDE_LAYOUT_TOKENS.CASE_STUDY,
};
