
// --------------------------------------------------------------------------------
// GOLDEN MODULE DATA SCHEMA (SINGLE SOURCE OF TRUTH)
// --------------------------------------------------------------------------------
// This schema defines the structure of the "Golden JSON" generated by the AI 
// for a single course module. It serves as the data source for all downstream 
// deliverables (Workbook, Manual, Slides, etc.).
// --------------------------------------------------------------------------------

export type CourseEnvironment = 'LIVE' | 'ONLINE';

/**
 * The root object generated by the AI for a single module.
 * Maps to the "God Prompt" output.
 */
export interface GoldenModuleData {
  // --- IMMUTABLE METADATA (From Blueprint) ---
  moduleId: string;
  moduleTitle: string;
  moduleDurationMinutes: number;
  environment: CourseEnvironment;

  // --- LOCALIZATION (Generated by AI) ---
  localizedLabels: {
    duration: string;         // e.g. "Duration" or "Durata"
    format: string;           // e.g. "Format" or "Format"
    section: string;          // e.g. "Section" or "Secțiunea"
    theory: string;           // e.g. "Theory & Concepts" or "Teorie & Concepte"
    keyTakeaways: string;     // e.g. "Key Takeaways" or "Idei Principale"
    actionPlan: string;       // e.g. "Action Plan" or "Plan de Acțiune"
    reflection: string;       // e.g. "Reflection" or "Reflecție"
    trainerInstructions: string; // e.g. "Trainer Instructions" or "Instrucțiuni Trainer"
    method: string;           // e.g. "Method" or "Metodă"
    logistics: string;        // e.g. "Logistics" or "Logistică"
    script: string;           // e.g. "Script" or "Script"
    activity: string;         // e.g. "Activity" or "Activitate"
    objective: string;        // e.g. "Objective" or "Obiectiv"
    instructionsParticipant: string; // e.g. "Participant Instructions"
    instructionsFacilitator: string; // e.g. "Facilitator Instructions"
    debrief: string;          // e.g. "Debrief" or "Debriefing"
    example: string;          // e.g. "Example" or "Exemplu"
    videoScript: string;      // e.g. "Video Script" or "Script Video"
  };

  // --- 1. GLOBAL NARRATIVE & EXAMPLES (File 6: Examples Library) ---
  // Context for the specific module within the larger story arc
  narrativeContext: {
    protagonistName: string; // e.g., "Marcela"
    storyArcStage: string;   // e.g., "The Conflict", "The Resolution"
    contextDescription: string; // Specific context for this module
    
    // A library of examples separate from the flow, for the trainer to use ad-hoc
    examplesLibrary: Array<{
      id: string;
      title: string;
      storyContent: string; // The full narrative/example
      applicationContext: string; // When to use this (e.g., "Use if participants ask about X")
    }>;
  };

  // --- 2. CONTENT FLOW (Atomic Sections) ---
  // Covers: Workbook, Manual, Slides, Exercises, Video Scripts
  sections: Array<GoldenSection>;
}

/**
 * An atomic section of the module (e.g., "Theory Block", "Exercise", "Debrief").
 * All facets of this section are generated simultaneously.
 */
export interface GoldenSection {
  id: string;
  title: string;
  durationMinutes: number;
  type: 'THEORY' | 'ACTIVITY' | 'DISCUSSION' | 'VIDEO_LESSON';

  // --- A. PARTICIPANT CONTENT (File 2: Workbook) ---
  participantContent: {
    theoryMarkdown: string; // Core concepts, definitions, "Why it matters"
    keyTakeaways: string[];
    reflectionQuestions?: string[];
    actionableSteps?: string[]; // "How to" steps
  };

  // --- B. TRAINER INSTRUCTIONS (File 3: Manual) ---
  trainerInstructions: {
    deliveryMethod: string;
    script: string; // Verbatim script for the trainer
    logistics: string[]; // Materials, setup
    
    // LIVE SPECIFIC: Visual aids for physical delivery
    flipchartSketch?: {
      title: string;
      visualDescription: string; // Instructions for what to draw
      bulletPoints: string[]; // Content to write on the chart
    };

    // ONLINE SPECIFIC: Virtual delivery configuration
    breakoutRoomConfig?: {
      groupSize: number;
      duration: number;
      taskDescription: string;
    };
  };

  // --- C. VISUALS (File 4: Slides) ---
  visuals: {
    slidesSequence: Array<{
      slideId: string;
      layout: 'TITLE' | 'BULLETS' | 'VISUAL_FOCUS' | 'QUOTE' | 'SPLIT_SCREEN';
      title: string;
      visualDescription: string; // Prompt for image generation or designer notes
      contentBullets: string[];
      speakerNotes: string; // Matches trainer script
    }>;
  };

  // --- D. DETAILED EXERCISES (File 5: Exercises Sheets) ---
  // Present ONLY if type === 'ACTIVITY' or 'DISCUSSION'
  exercisesDetailed?: {
    title: string;
    objective: string;
    durationMinutes: number;
    
    // Step-by-step guides
    instructionsParticipant: string;
    instructionsFacilitator: string;
    
    materialsNeeded: string[];
    
    // The "Answer Key" or specific things to look for
    debriefingQuestions: string[];
    successIndicators: string[]; // "Participants should be able to..."
    
    // Adaptation for environment
    adaptationNotes: string; // e.g., "In Online, use Chat for step 2"
  };

  // --- E. VIDEO SCRIPT (File 7: Video Script - Online Only) ---
  // Present ONLY if environment === 'ONLINE' and type === 'VIDEO_LESSON'
  videoScript?: {
    sceneDescription: string; // "Trainer facing camera, graphics overlay"
    scriptContent: string; // The exact words for the video recording
    visualOverlays: Array<{
      timestamp: string; // Approximate relative time e.g., "00:30"
      description: string; // "Show definition of Leadership"
    }>;
  };
}
