-- Add 'dna' column to 'courses' table to store Course DNA structure
ALTER TABLE courses ADD COLUMN IF NOT EXISTS dna JSONB DEFAULT NULL;

-- Comment on column
COMMENT ON COLUMN courses.dna IS 'Stores the Course DNA (terminology, narrative universe, voice profile) generated by AI';
